version: "3.4"

services:
  weather-sql-server-test:
    image: postgres:14.1
    command: ["postgres", "-c", "log_statement=${DB_LOG_LEVEL:-all}"]
    restart: "no"
    ports:
      - ${DB_PORT_TEST:-5431}:5432
    environment:
      - POSTGRES_USER=${DB_USER_TEST:-WeatherAppUserTest}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST:-WeatherAppUserSecretTest}
      - POSTGRES_DB=${DB_DATABASE_TEST:-WeatherTest}
